/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author carthur
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    Double num1;
    Double num2;
    Double resultado;
    String operador;
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResultado = new javax.swing.JTextField();
        btnCE = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnPM = new javax.swing.JButton();
        btnDigito8 = new javax.swing.JButton();
        btnDigito7 = new javax.swing.JButton();
        btnDigito9 = new javax.swing.JButton();
        btnSinalMais = new javax.swing.JButton();
        btnDigito5 = new javax.swing.JButton();
        btnDigito4 = new javax.swing.JButton();
        btnDigito6 = new javax.swing.JButton();
        btnSinalMenos = new javax.swing.JButton();
        btnDigito2 = new javax.swing.JButton();
        btnDigito1 = new javax.swing.JButton();
        btnDigito3 = new javax.swing.JButton();
        btnSinalMultiplicacao = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btnDigito0 = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnSinalDivisao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResultado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        btnCE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/icons8-limpar-símbolo-30.png"))); // NOI18N
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnPM.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPM.setText("±");
        btnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMActionPerformed(evt);
            }
        });

        btnDigito8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito8.setText("8");
        btnDigito8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito8ActionPerformed(evt);
            }
        });

        btnDigito7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito7.setText("7");
        btnDigito7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito7ActionPerformed(evt);
            }
        });

        btnDigito9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito9.setText("9");
        btnDigito9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito9ActionPerformed(evt);
            }
        });

        btnSinalMais.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSinalMais.setText("+");
        btnSinalMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinalMaisActionPerformed(evt);
            }
        });

        btnDigito5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito5.setText("5");
        btnDigito5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito5ActionPerformed(evt);
            }
        });

        btnDigito4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito4.setText("4");
        btnDigito4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito4ActionPerformed(evt);
            }
        });

        btnDigito6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito6.setText("6");
        btnDigito6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito6ActionPerformed(evt);
            }
        });

        btnSinalMenos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSinalMenos.setText("-");
        btnSinalMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinalMenosActionPerformed(evt);
            }
        });

        btnDigito2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito2.setText("2");
        btnDigito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito2ActionPerformed(evt);
            }
        });

        btnDigito1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito1.setText("1");
        btnDigito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito1ActionPerformed(evt);
            }
        });

        btnDigito3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito3.setText("3");
        btnDigito3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito3ActionPerformed(evt);
            }
        });

        btnSinalMultiplicacao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSinalMultiplicacao.setText("*");
        btnSinalMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinalMultiplicacaoActionPerformed(evt);
            }
        });

        btnDecimal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDecimal.setText(".");
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });

        btnDigito0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDigito0.setText("0");
        btnDigito0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigito0ActionPerformed(evt);
            }
        });

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCalcular.setText("=");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnSinalDivisao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSinalDivisao.setText("/");
        btnSinalDivisao.setToolTipText("");
        btnSinalDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinalDivisaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtResultado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDigito7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDigito8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDigito9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnSinalMais, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDigito4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDigito5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDigito6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnSinalMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDigito1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDigito2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDigito3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnSinalMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDigito0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnSinalDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDigito8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigito7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigito9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinalMais, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDigito5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigito4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigito6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinalMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDigito2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigito1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigito3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinalMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigito0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinalDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaNumeros(String q) {
        String Nums = txtResultado.getText() + q;
        txtResultado.setText(Nums);
    }
    
    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        String apagar = null;
        
        if (txtResultado.getText().length() > 0) {
            StringBuilder sb = new StringBuilder(txtResultado.getText());
            sb.deleteCharAt(txtResultado.getText().length() - 1);
            apagar = sb.toString();
            txtResultado.setText(apagar);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMActionPerformed
        double nums = Double.parseDouble(String.valueOf(txtResultado.getText()));
        nums = nums * (-1);
        txtResultado.setText(String.valueOf(nums));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPMActionPerformed

    private void btnDigito7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito7ActionPerformed
        EntradaNumeros("7");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito7ActionPerformed

    private void btnDigito8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito8ActionPerformed
        EntradaNumeros("8");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito8ActionPerformed

    private void btnDigito9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito9ActionPerformed
        EntradaNumeros("9");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito9ActionPerformed

    private void btnDigito4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito4ActionPerformed
        EntradaNumeros("4");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito4ActionPerformed

    private void btnDigito5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito5ActionPerformed
        EntradaNumeros("5");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito5ActionPerformed

    private void btnDigito6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito6ActionPerformed
        EntradaNumeros("6");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito6ActionPerformed

    private void btnDigito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito1ActionPerformed
        EntradaNumeros("1");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito1ActionPerformed

    private void btnDigito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito2ActionPerformed
        EntradaNumeros("2");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito2ActionPerformed

    private void btnDigito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito3ActionPerformed
        EntradaNumeros("3");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito3ActionPerformed

    private void btnDigito0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigito0ActionPerformed
        EntradaNumeros("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigito0ActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        txtResultado.setText("");
        num1 = 0d;
        
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void btnSinalDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinalDivisaoActionPerformed
        num1 = Double.parseDouble(txtResultado.getText());
        txtResultado.setText("");
   
        operador = "/";
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSinalDivisaoActionPerformed

    private void btnSinalMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinalMultiplicacaoActionPerformed
        num1 = Double.parseDouble(txtResultado.getText());
        txtResultado.setText("");
       
        operador = "*";
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSinalMultiplicacaoActionPerformed

    private void btnSinalMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinalMenosActionPerformed
        num1 = Double.parseDouble(txtResultado.getText());
        txtResultado.setText("");
        
        operador = "-";
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSinalMenosActionPerformed

    private void btnSinalMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinalMaisActionPerformed
       num1 = Double.parseDouble(txtResultado.getText());
        txtResultado.setText("");
        
        operador = "+";
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSinalMaisActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        txtResultado.setText("");
        
        
        String Pn, Sn;
        Pn = String.valueOf(num1);
        Sn = String.valueOf(num2);
        
        Pn = "";
        Sn = "";
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        if (!txtResultado.getText().contains(".")){
            txtResultado.setText(txtResultado.getText() + btnDecimal.getText());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDecimalActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        num2 = Double.parseDouble(txtResultado.getText());
        if (operador == "+") {
            resultado = num1 + num2;
        }
        else if (operador == "-") {
            resultado = num1 - num2;
        }
        else if (operador == "*") {
            resultado = num1 * num2;
        }
        else {
            resultado = num1 / num2;
        }
        txtResultado.setText(resultado.toString());
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnDigito0;
    private javax.swing.JButton btnDigito1;
    private javax.swing.JButton btnDigito2;
    private javax.swing.JButton btnDigito3;
    private javax.swing.JButton btnDigito4;
    private javax.swing.JButton btnDigito5;
    private javax.swing.JButton btnDigito6;
    private javax.swing.JButton btnDigito7;
    private javax.swing.JButton btnDigito8;
    private javax.swing.JButton btnDigito9;
    private javax.swing.JButton btnPM;
    private javax.swing.JButton btnSinalDivisao;
    private javax.swing.JButton btnSinalMais;
    private javax.swing.JButton btnSinalMenos;
    private javax.swing.JButton btnSinalMultiplicacao;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
